In [ ]:
#References
#https://github.com/sghosh246/DSM_Session22_Assignment_22.1/blob/master/Logistic_Regression_to_predict_woman_affair.ipynb
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
#https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score

In [ ]:
dta = sm.datasets.fair.load_pandas().data

In [ ]:
dta.head()

rate_marriage   age  yrs_married  ...  occupation  occupation_husb   affairs
0            3.0  32.0          9.0  ...         2.0              5.0  0.111111
1            3.0  27.0         13.0  ...         3.0              4.0  3.230769
2            4.0  22.0          2.5  ...         3.0              5.0  1.400000
3            4.0  37.0         16.5  ...         5.0              5.0  0.727273
4            5.0  27.0          9.0  ...         3.0              4.0  4.666666

[5 rows x 9 columns]

In [ ]:
dta.columns

Index(['rate_marriage', 'age', 'yrs_married', 'children', 'religious', 'educ',
       'occupation', 'occupation_husb', 'affairs'],
      dtype='object')

In [ ]:
dta['affair']=(dta.affairs>0).astype(int)

In [ ]:
dta.head()

rate_marriage   age  yrs_married  ...  occupation_husb   affairs  affair
0            3.0  32.0          9.0  ...              5.0  0.111111       1
1            3.0  27.0         13.0  ...              4.0  3.230769       1
2            4.0  22.0          2.5  ...              5.0  1.400000       1
3            4.0  37.0         16.5  ...              5.0  0.727273       1
4            5.0  27.0          9.0  ...              4.0  4.666666       1

[5 rows x 10 columns]

In [ ]:
dta['affair'].unique()

array([1, 0])

In [ ]:
y, X = dmatrices('affair ~ rate_marriage + age + yrs_married + children +  religious + educ + C(occupation) + C(occupation_husb)',dta, return_type="dataframe")
X = X.rename(columns =
{'C(occupation)[T.2.0]':'occ_2',
'C(occupation)[T.3.0]':'occ_3',
'C(occupation)[T.4.0]':'occ_4',
'C(occupation)[T.5.0]':'occ_5',
'C(occupation)[T.6.0]':'occ_6',
'C(occupation_husb)[T.2.0]':'occ_husb_2',
'C(occupation_husb)[T.3.0]':'occ_husb_3',
'C(occupation_husb)[T.4.0]':'occ_husb_4',
'C(occupation_husb)[T.5.0]':'occ_husb_5',
'C(occupation_husb)[T.6.0]':'occ_husb_6'})

y = np.ravel(y)
y

array([1., 1., 1., ..., 0., 0., 0.])

In [ ]:
X

Intercept  occ_2  occ_3  occ_4  ...  yrs_married  children  religious  educ
0           1.0    1.0    0.0    0.0  ...          9.0       3.0        3.0  17.0
1           1.0    0.0    1.0    0.0  ...         13.0       3.0        1.0  14.0
2           1.0    0.0    1.0    0.0  ...          2.5       0.0        1.0  16.0
3           1.0    0.0    0.0    0.0  ...         16.5       4.0        3.0  16.0
4           1.0    0.0    1.0    0.0  ...          9.0       1.0        1.0  14.0
...         ...    ...    ...    ...  ...          ...       ...        ...   ...
6361        1.0    0.0    0.0    1.0  ...         13.0       2.0        3.0  17.0
6362        1.0    0.0    0.0    0.0  ...         13.0       1.0        1.0  16.0
6363        1.0    0.0    1.0    0.0  ...          2.5       0.0        2.0  14.0
6364        1.0    0.0    1.0    0.0  ...          6.0       1.0        3.0  14.0
6365        1.0    1.0    0.0    0.0  ...          2.5       0.0        2.0  16.0

[6366 rows x 17 columns]

In [ ]:
X.columns

Index(['Intercept', 'occ_2', 'occ_3', 'occ_4', 'occ_5', 'occ_6', 'occ_husb_2',
       'occ_husb_3', 'occ_husb_4', 'occ_husb_5', 'occ_husb_6', 'rate_marriage',
       'age', 'yrs_married', 'children', 'religious', 'educ'],
      dtype='object')

In [ ]:
X_train, X_test , y_train , y_test = train_test_split(X , y , test_size = 0.25 , random_state= 4) 
model = LogisticRegression() 
model = model.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
predicted=model.predict(X_test)
predicted


array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
np.unique(predicted)

array([0., 1.])

In [ ]:
probability = model.predict_proba(X_test)
probability

array([[0.83583598, 0.16416402],
       [0.79237025, 0.20762975],
       [0.67567895, 0.32432105],
       ...,
       [0.83617569, 0.16382431],
       [0.76672441, 0.23327559],
       [0.83402863, 0.16597137]])

In [ ]:
a=(metrics.accuracy_score(y_test, predicted))
b=(metrics.roc_auc_score(y_test, probability[:, 1]))
a

0.7066582914572864

In [ ]:
b

0.7266640370594507

In [ ]:
c=(metrics.confusion_matrix(y_test, predicted))
d=(metrics.classification_report(y_test, predicted))

In [ ]:
c

array([[957, 119],
       [348, 168]])

In [ ]:
d

'              precision    recall  f1-score   support\n\n         0.0       0.73      0.89      0.80      1076\n         1.0       0.59      0.33      0.42       516\n\n    accuracy                           0.71      1592\n   macro avg       0.66      0.61      0.61      1592\nweighted avg       0.69      0.71      0.68      1592\n'

In [ ]:
scores = cross_val_score(LogisticRegression(), X, y, cv=5)
scores

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.71036107, 0.72427337, 0.71877455, 0.72034564, 0.75098193])

In [ ]:
scores.mean()

0.7249473116940293