In [ ]:
import numpy as np
a=np.array([1,2,3,4])
n=4
mat=np.column_stack([a**(n-i-1) for i in range(n)])
mat

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [ ]:
a=np.array([1,2,3,4])
np.vander(a)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [ ]:
a=np.array([1,2,3,4,5,6])
ret=np.cumsum(a)
ret

array([ 1,  3,  6, 10, 15, 21])

In [ ]:
ret[1:]

array([ 3,  6, 10, 15, 21])

In [ ]:
a = ret[3:] - ret[:-3]
a

array([ 6,  3, -3])

In [ ]:
def mov_avg_val(mylist, N):
    cumsum, moving_aves = [0], []
    for i,x in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] +x) # summing up all the values one by one and appending the list
        if i>=N:
            moving_ave = round(((cumsum[i] - cumsum[i-N])/N),2) #computing the moving average using temp array sum array cumsum
            #can do stuff with moving_ave here
            moving_aves.append(moving_ave) # listing the moving average as an single array
    print("Moving average values list: ", moving_aves)
    print("Length of the list l-N+1: ", len(moving_aves))

In [ ]:
mylist = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
N = 4

mov_avg_val(mylist,N)


Moving average values list:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
Length of the list l-N+1:  7


In [ ]:
asum=[1,2,3,4,5,6,7,8,9,10]
asum[:-3]

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [ ]:
a = np.arange(20)
np.array(moving_average(a,n=3).round(2))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])